### ISSUE TITLE
The code stuck on the 84 line in the train.py file

### ISSUE THREAD

**Issue by leeruibin** [wouterkool/attention-learn-to-route#11]
When I run the code, it stuck on the 84 line in the train.py file

for batch_id, batch in enumerate(tqdm(training_dataloader, disable=opts.no_progress_bar)):

I found the number of dateset is 1280000, but it seems that it takes to long for the enumerate process, the code can not even go into the for loop, I run the code for about 1 hour, it still can not go into the loop process the execute the train_bitch() line. 
Can you help me with this problem?

**Comment by SaeidKalantari** [comment]
Hi, I had the same issue, and here is how I solved it:
Turns out this is related to the **'num_workers=1'**. If you change it to **'num_workers=0'** the code will run properly. This is in line 78 of **'train.py'**:
`training_dataloader = DataLoader(training_dataset, batch_size=opts.batch_size, num_workers=1)`
At first, I thought this is because of 'enumerate', but it is not.
I hope this solves it for you.
Cheers
