### ISSUE TITLE
Methods to build the context embedding and query

### ISSUE THREAD

**Issue by YunqiuXu** [wouterkool/attention-learn-to-route#13]
Hi Wouter,

Thanks for sharing the code, I've tried it and the result is quite promising :D
But I found that the method to build the context embedding as well as query may be different from the paper. In the paper it's built via horizontal concatenation:

![kool2019_question](https://user-images.githubusercontent.com/15887968/71666693-f1c85a00-2d59-11ea-81b5-5d9d4b6bbba9.png)

But in the code it seems that the projected graph embedding is added on the projected start and end nodes
https://github.com/wouterkool/attention-learn-to-route/blob/master/nets/attention_model.py#L349

Are these differences matter?

**Comment by wouterkool** [comment]
Hi,

Concatenating and then projecting linearly (as intuitive to understand and described in the paper) is equivalent to projecting and then summing (as used in the code but this indeed could use some explanation), see also example below.

Using the implementation in the code , you can precompute the projection of the graph embedding, which is slightly more efficient. Note that there may be small effects of different initialisation by having three weight matrices instead of 1.

```
>>> import numpy as np
>>> W1, W2, W3 = [np.random.rand(5, 3) for i in range(3)]
>>> h1, h2, h3 = [np.random.rand(3) for i in range(3)]
>>> np.dot(W1, h1) + np.dot(W2, h2) + np.dot(W3, h3)
array([0.98143469, 0.72001267, 0.91826991, 0.62929778, 0.70220116])
>>> np.dot(np.hstack((W1, W2, W3)), np.concatenate((h1, h2, h3)))
array([0.98143469, 0.72001267, 0.91826991, 0.62929778, 0.70220116])
```

**Comment by YunqiuXu** [comment]
Got it, thanks for explaining
