### ISSUE TITLE
Problem with enumerate(tqdm(training_dataloader...))

### ISSUE THREAD

**Issue by ruihuang1967** [wouterkool/attention-learn-to-route#14]
Hi there,

I very much enjoy your paper. I try to run the code but it somehow stuck at:

_enumerate(tqdm(training_dataloader, disable=opts.no_progress_bar))_

I ran the code on Windows using anaconda. Can you please let me know if that is just normal and all I have to do is to wait?

Thanks.

**Comment by SaeidKalantari** [comment]
Hi, I had the same issue, and here is how I solved it:
Turns out this is related to the **'num_workers=1'**. If you change it to **'num_workers=0'** the code will run properly. This is in line 78 of **'train.py'**:
`training_dataloader = DataLoader(training_dataset, batch_size=opts.batch_size, num_workers=1)`
At first, I thought this is because of 'enumerate', but it is not.
I hope this solves it for you.
Cheers
