### ISSUE TITLE
Runtime Error in Python 3.8

### ISSUE THREAD

**Issue by mlisicki** [wouterkool/attention-learn-to-route#16]
After switching to Python 3.8 I'm getting "RuntimeError: __class__ not set defining 'BatchBeam' as <class 'utils.beam_search.BatchBeam'>. Was __classcell__ propagated to type.__new__?"

After reading this post https://stackoverflow.com/questions/41343263/provide-classcell-example-for-python-3-6-metaclass and doing some initial debugging I'm guessing there should be some more arguments passed to super() method whenever you use it. It seems that all the classes deriving from NamedTuple are affected.

**Comment by mlisicki** [comment]
A minimal example that causes the error:

```
from typing import NamedTuple

class SuperTuple(NamedTuple):
    def __getitem__(self, key):
        return super(SuperTuple, self).__getitem__(key)
```

**Comment by emeccc** [comment]
@mlisicki I am getting the same error as yours after switching to Python 3.8. How did you solve this problem?

**Comment by wouterkool** [comment]
@mlisicki thanks for your investigations! Where you able to solve it in the end?

**Comment by gabisurita** [comment]
I was able to run the basic example by changing:

```python
return super(SuperTuple, self).__getitem__(key)
```
With only:

```python
return self[key]
```

Not sure if I've broke anything else though. I'll try to validate and maybe run more tests.

**Comment by wouterkool** [comment]
Thanks for notifying this issue and proposing solutions. The code was intended to have the __getitem__ functionality fall back to default when the objects are not indexed with slices or tensors. While the suggestions by @gabisurita fixes the error message by removing `super`, the `self[key]` has actually no effect (since it is never reached currently) but would cause an infinite recursion. Therefore, I implemented an assert instead.
